# Conda environment for Gammapy version 2.0.1
# Install:    conda env create -f gammapy-2.0.1-environment.yml
# Activate:   conda activate gammapy-2.0.1
# Deactivate: conda deactivate

name: gammapy-2.0.1

channels:
  - conda-forge

variables:
  PYTHONNOUSERSITE: "1"

dependencies:
  - python=3.12
  - gammapy=2.0.1
  - ipython=8.27
  - cython
  - jupyter
  - jupyterlab=4.5
  - pyyaml=6.0
  - click=8.2
  - numpy=2.3
  - scipy=1.16
  - pandas=2.3
  - matplotlib=3.9
  - astropy=7.2
  - regions=0.10
  - iminuit=2.32
  - healpy=1.18
  - naima=0.10
  - pydantic=2.11
  - corner=2.2
  - pip
  - requests
  - tqdm
  - pip:
    - ray[default]~=2.48.0
